# The enemies table, generated by tables.check write=true from its schema;
# write it again rather than by hand (polyweave, §PW364).
extends RefCounted

const FILE := "res://data/enemies.csv"
const KEY := "id"
const COLUMNS := {"id": "string", "hp": "int", "speed": "float", "flies": "bool", "kind": "string"}


class Row:
	var id: String
	var hp: int
	var speed: float
	var flies: bool
	var kind: String


## each row, typed as the schema declares it
static func read() -> Array:
	var out := []
	for values in load("res://addons/polyweave/tables/tables.gd").values_of(FILE, COLUMNS):
		var row := Row.new()
		for column in values:
			row.set(column, values[column])
		out.append(row)
	return out
