// GENERATED by scripts/roadmap.mjs from docs/ROADMAP.md, through roadkeep. Do not edit.
// `npm run generate` rewrites this file; `npm test` fails if it drifted from the roadmap.

export interface GeneratedBlock {
  /** the single letter the roadmap files it under */
  block: string;
  title: string;
  /** lines still open in that block */
  open: number;
}

export interface GeneratedTask {
  id: string;
  block: string;
  /** the failure the line exists to remove, in the roadmap's own words */
  symptom: string;
  /** the measurement or the argument behind it */
  why: string;
  deps: string[];
}

export interface GeneratedNonGoal {
  lead: string;
  why: string;
}

export const generatedBlocks: GeneratedBlock[] = [
  { block: "A", title: "What a tool call costs the turn", open: 6 },
  { block: "B", title: "Seeing the result cheaply", open: 2 },
  { block: "C", title: "The asset compiler", open: 2 },
  { block: "D", title: "Fetching from a paid service without surprise", open: 6 },
  { block: "E", title: "One world with the engine", open: 4 },
  { block: "F", title: "Motion", open: 4 },
  { block: "G", title: "Geometry as a declaration", open: 5 },
  { block: "H", title: "Proof on a real game", open: 2 },
];

export const generatedTasks: GeneratedTask[] = [
  {
    id: "PW37",
    block: "A",
    symptom: "a renderer outlives the worker that started it, and a sweep on Windows cannot find it to end it",
    why: "taskkill walks a tree from the living parent, so a worker that died takes its handle to its children with it, and the render goes on spending a core nobody is watching.",
    deps: [],
  },
  {
    id: "PW38",
    block: "A",
    symptom: "a height field survives an eight-bit round trip as a staircase, and every assertion says it is fine",
    why: "The third silent failure behind the post-conditions is a blur that quantises a gradient, invisible in a shadow and ruinous under a specular, and no colour or coverage check sees it.",
    deps: [],
  },
  {
    id: "PW39",
    block: "A",
    symptom: "a job checks only that an argument exists while a direct call checks its range, so one call has two contracts",
    why: "The worker reads a target's signature and describe reads its registration, so a value the surface would refuse still costs a spawn and a failed job to discover.",
    deps: [],
  },
  {
    id: "PW40",
    block: "A",
    symptom: "a tolerance has one default in the project config and a different one in the function that uses it",
    why: "A check falls back to an alpha floor of zero while the config declares 0.02, so an operation that forgets to pass it measures the background as part of the subject.",
    deps: [],
  },
  {
    id: "PW41",
    block: "A",
    symptom: "an artefact that was produced without a record is invisible, because verify starts from the records",
    why: "A paid mesh with no sidecar reads as a sound project, and re-buying it is the only way to find out what it was made from.",
    deps: [],
  },
  {
    id: "PW42",
    block: "A",
    symptom: "a render that is black to any observer passes the check for a blank render, on one bit of edge noise",
    why: "The assertion asks whether every visible pixel is exactly one colour, and an unlit Cycles render came back with two: black, and 1/255 at the antialiased edge.",
    deps: [],
  },
  {
    id: "PW43",
    block: "B",
    symptom: "a colour measured off a render is not the colour that was authored, and nothing says so",
    why: "An emission that should land on sRGB 128 came back at 161, and at 172 after asking for the standard view transform, because this Blender ships without the colour configuration.",
    deps: [],
  },
  {
    id: "PW44",
    block: "B",
    symptom: "one configured noise floor calls every preview-sized render a change, because the floor moves with the rung",
    why: "Two seeds of one scene measured 0.046 apart at four samples and 0.014 at sixty-four, against a configured default of 0.004 calibrated for a final render.",
    deps: [],
  },
  {
    id: "PW15",
    block: "C",
    symptom: "a search reports the winning numbers and not what it rejected",
    why: "A result nobody can inspect is one nobody can overrule, and a rig tuned against the wrong criterion looks exactly like a rig tuned against the right one.",
    deps: [],
  },
  {
    id: "PW45",
    block: "C",
    symptom: "a search renders its samples one after another, so a budget of twenty-four costs twenty-four waits",
    why: "The job handles exist so four samples can run at once, and the search calls its evaluator once per sample and waits for each render before proposing the next.",
    deps: [],
  },
  {
    id: "PW16",
    block: "D",
    symptom: "a generated mesh's silhouette is checked after its credits are spent",
    why: "A wide low cap was sent and a tall dome on a long stem came back, which is thirty credits to learn something a silhouette check would have shown for nothing.",
    deps: [],
  },
  {
    id: "PW17",
    block: "D",
    symptom: "a paid asset is deleted by the service seventy-two hours after it is made",
    why: "One run recorded the settings it proved and not the mesh, and the mesh is now gone, so the receipt outlived the thing that was bought.",
    deps: [],
  },
  {
    id: "PW18",
    block: "D",
    symptom: "every fetch needs a human decision, so work stops between approvals",
    why: "The rule that an agent may not spend on its own judgement is right, but it is enforced by asking each time rather than by a ceiling agreed once.",
    deps: ["PW17"],
  },
  {
    id: "PW19",
    block: "D",
    symptom: "an unknown field is dropped in silence, so a payload that validates proves nothing",
    why: "Learning the schema takes a series of deliberately invalid values, each carrying a made-up field as its control, and none of that knowledge is kept anywhere.",
    deps: [],
  },
  {
    id: "PW20",
    block: "D",
    symptom: "a fetched mesh arrives at an arbitrary orientation, scale and origin",
    why: "The service returned a hammer standing upright where the drawing leans it, and the correction was two angles found by re-rendering until it looked right.",
    deps: [],
  },
  {
    id: "PW21",
    block: "D",
    symptom: "a reference photograph brings whatever stood behind the subject back as geometry",
    why: "A picture of a plush toy returned the logo the toy was sitting on, fused into the mesh, and no camera move takes it back out again.",
    deps: [],
  },
  {
    id: "PW22",
    block: "E",
    symptom: "the engine's exit code is not the verdict, so each project writes its own output parser",
    why: "Godot exits zero on a script error and non-zero on a clean quit, so the only honest signal is a line the script printed and no error in the log.",
    deps: [],
  },
  {
    id: "PW23",
    block: "E",
    symptom: "a real renderer needs a window, so a capture cannot run where there is no screen",
    why: "Headless mode draws nothing at all, which makes every screenshot a manual step on a developer's desk and keeps it out of any gate.",
    deps: ["PW22"],
  },
  {
    id: "PW24",
    block: "E",
    symptom: "the baked sprite and the running game agree on scale only because a constant was tuned",
    why: "One unit is one pixel because somebody set the render rectangle to match a cell size the game holds separately, and nothing fails if either moves.",
    deps: [],
  },
  {
    id: "PW25",
    block: "E",
    symptom: "a capture takes its picture in whatever language and settings the runner happens to have",
    why: "The same script on two machines produces two different images, and the difference is a locale nobody declared rather than a change anybody made.",
    deps: ["PW22"],
  },
  {
    id: "PW26",
    block: "F",
    symptom: "a fetched mesh has no skeleton, so it cannot be posed at all",
    why: "Every generative mesh arrives as a static surface, and rigging one by hand is the step that keeps character animation out of reach entirely.",
    deps: [],
  },
  {
    id: "PW27",
    block: "F",
    symptom: "motion is expressed as a second static render, so nothing longer than two frames exists",
    why: "A settle is a squashed re-render of the same mesh, which is right for one beat and has no way to say what a walk or a reaction would be.",
    deps: ["PW26"],
  },
  {
    id: "PW28",
    block: "F",
    symptom: "an animation lives in a binary track, so a curve cannot be reviewed or edited as text",
    why: "A timing change inside a mesh file is invisible in a diff and unreachable by an edit, which makes every adjustment a re-export from a tool nobody scripted.",
    deps: ["PW27"],
  },
  {
    id: "PW29",
    block: "F",
    symptom: "a 2D screen needs frames and a 3D scene needs a clip, so the motion is authored twice",
    why: "The same settle exists as a sprite the interface crossfades to and as something a 3D scene would play, and keeping the two in step is manual.",
    deps: ["PW27"],
  },
  {
    id: "PW30",
    block: "G",
    symptom: "a shape is a Python script, so stating one means writing and debugging a program",
    why: "Cottony's tray, star, ball and props are four modules of imperative geometry code, and the shape each describes is not readable without running it.",
    deps: [],
  },
  {
    id: "PW31",
    block: "G",
    symptom: "a format covering only primitives would leave every real asset in code",
    why: "The existing models use extruded outlines, crowned plates, radial arrays, annuli and boolean pockets, so the vocabulary has to be read off what they already do.",
    deps: ["PW30"],
  },
  {
    id: "PW32",
    block: "G",
    symptom: "a shape's own numbers are unreachable from the search that tunes everything else",
    why: "Geometry constants live inside a module while the rig's live in a dataclass, so a search can reach the lighting and never the shape it is lighting.",
    deps: ["PW30"],
  },
  {
    id: "PW33",
    block: "G",
    symptom: "a shape cannot be reviewed without building it, so a wrong construction is found in the render",
    why: "Two wrong constructions of one tray's seats each looked reasonable while being written and were only visible once rendered, which is the expensive place.",
    deps: ["PW30"],
  },
  {
    id: "PW34",
    block: "G",
    symptom: "a declaration that cannot express a shape leaves no way back to code",
    why: "Any format will meet a shape it cannot state, and forcing that shape into the format produces worse geometry than the script it replaced.",
    deps: ["PW30"],
  },
  {
    id: "PW35",
    block: "H",
    symptom: "the plugin's value is asserted and never measured against what it replaced",
    why: "Nothing records how long a correct asset took before or after, so there is no way to tell a real improvement from a rearrangement of the same work.",
    deps: [],
  },
  {
    id: "PW36",
    block: "H",
    symptom: "a real project cannot adopt the plugin without carrying its own paths and palette into it",
    why: "Cottony is the first consumer and the test of whether the configuration boundary holds, and an adoption that needs a fork proves that it does not.",
    deps: [],
  },
];

export const generatedNonGoals: GeneratedNonGoal[] = [
  {
    lead: "A graphical editor",
    why: "The caller here is an agent in a terminal, so a surface that needs a person at a screen to operate is one the agent cannot use at all.",
  },
  {
    lead: "Replacing Blender, Godot or the generative service",
    why: "Those three already do the work; what is missing is the loop around them, so this orchestrates and measures and never re-implements a renderer, an engine or a mesh generator.",
  },
  {
    lead: "Spending money on the agent's own judgement",
    why: "A fetch draws on a real balance, so the ceiling is a person's to set and the plugin's job is to make a spend bounded and visible, never to decide one is worth it.",
  },
  {
    lead: "One project's palette, rig or paths compiled in",
    why: "Cottony is the first consumer and not the specification, so anything it needs that a second project would not is configuration, and a default that cannot be overridden is a defect.",
  },
  {
    lead: "A hosted service or an account to sign into",
    why: "Everything runs on the developer's machine against files in their own repository, because a plugin that needs an account is one that fails on the day the account does.",
  },
];
