// GENERATED by scripts/roadmap.mjs from docs/ROADMAP.md, through roadkeep. Do not edit.
// `npm run generate` rewrites this file; `npm test` fails if it drifted from the roadmap.

export interface GeneratedBlock {
  /** the single letter the roadmap files it under */
  block: string;
  title: string;
  /** lines still open in that block */
  open: number;
}

export interface GeneratedTask {
  id: string;
  block: string;
  /** the failure the line exists to remove, in the roadmap's own words */
  symptom: string;
  /** the measurement or the argument behind it */
  why: string;
  deps: string[];
}

export interface GeneratedNonGoal {
  lead: string;
  why: string;
}

export const generatedBlocks: GeneratedBlock[] = [
  { block: "A", title: "What a tool call costs the turn", open: 2 },
  { block: "B", title: "Seeing the result cheaply", open: 2 },
  { block: "C", title: "The asset compiler", open: 1 },
  { block: "D", title: "Fetching from a paid service without surprise", open: 2 },
  { block: "E", title: "One world with the engine", open: 1 },
  { block: "F", title: "Motion", open: 0 },
  { block: "G", title: "Geometry as a declaration", open: 1 },
  { block: "H", title: "Proof on a real game", open: 1 },
];

export const generatedTasks: GeneratedTask[] = [
  {
    id: "PW51",
    block: "A",
    symptom: "a record says nothing about the tolerances its measurements were taken against",
    why: "Reading the config back gives the project's numbers now, not the artefact's, so two records carrying one measurement can mean different things and nothing says which.",
    deps: [],
  },
  {
    id: "PW52",
    block: "A",
    symptom: "a render holding two opaque pixels in one corner is empty for every purpose and passes every check",
    why: "Coverage clears the alpha floor and the two pixels differ, so neither assertion fires, and the obvious number to compare against would refuse a correctly framed thin asset.",
    deps: [],
  },
  {
    id: "PW43",
    block: "B",
    symptom: "a colour measured off a render is not the colour that was authored, and nothing says so",
    why: "An emission that should land on sRGB 128 came back at 161, and at 172 after asking for the standard view transform, because this Blender ships without the colour configuration.",
    deps: [],
  },
  {
    id: "PW44",
    block: "B",
    symptom: "one configured noise floor calls every preview-sized render a change, because the floor moves with the rung",
    why: "Two seeds of one scene measured 0.046 apart at four samples and 0.014 at sixty-four, against a configured default of 0.004 calibrated for a final render.",
    deps: [],
  },
  {
    id: "PW45",
    block: "C",
    symptom: "a search renders its samples one after another, so a budget of twenty-four costs twenty-four waits",
    why: "The job handles exist so four samples can run at once, and the search calls its evaluator once per sample and waits for each render before proposing the next.",
    deps: [],
  },
  {
    id: "PW46",
    block: "D",
    symptom: "a normalised mesh sits beside the paid one with nothing recording what it derives from",
    why: "Ingest writes a second file and returns the transform to its caller, so the mesh the project loads is one `verify` reads as an artefact nothing recorded.",
    deps: [],
  },
  {
    id: "PW49",
    block: "D",
    symptom: "a fetched mesh arrives with shading painted into its texture, and nothing can take the marks back out",
    why: "Those marks are shadows that do not move when the light does, and Cottony had to keep its own scrub pass with three thresholds found by eye, which is the fork adoption tests for.",
    deps: [],
  },
  {
    id: "PW47",
    block: "E",
    symptom: "a bake renders square at the rung's size, so a declared world rectangle can be refused but never met",
    why: "PW24's contract names the size a sprite must be, and nothing renders at it: the size is the rung's, and it is not in the cache key either.",
    deps: [],
  },
  {
    id: "PW50",
    block: "G",
    symptom: "a fuzzy surface cannot be declared at all, because shell texturing is a technique and no table holds one",
    why: "Cottony's plush look is eight constants found by eye, and a table of eight keys would be one project's look compiled in while helping nobody who wanted fur instead.",
    deps: [],
  },
  {
    id: "PW48",
    block: "H",
    symptom: "every test input is synthetic, so nothing is ever checked against an artefact somebody made",
    why: "The suite has no real mesh, photograph or capture in it, and those are where every symptom in this backlog was measured in the first place.",
    deps: [],
  },
];

export const generatedNonGoals: GeneratedNonGoal[] = [
  {
    lead: "A graphical editor",
    why: "The caller here is an agent in a terminal, so a surface that needs a person at a screen to operate is one the agent cannot use at all.",
  },
  {
    lead: "Replacing Blender, Godot or the generative service",
    why: "Those three already do the work; what is missing is the loop around them, so this orchestrates and measures and never re-implements a renderer, an engine or a mesh generator.",
  },
  {
    lead: "Spending money on the agent's own judgement",
    why: "A fetch draws on a real balance, so the ceiling is a person's to set and the plugin's job is to make a spend bounded and visible, never to decide one is worth it.",
  },
  {
    lead: "One project's palette, rig or paths compiled in",
    why: "Cottony is the first consumer and not the specification, so anything it needs that a second project would not is configuration, and a default that cannot be overridden is a defect.",
  },
  {
    lead: "A hosted service or an account to sign into",
    why: "Everything runs on the developer's machine against files in their own repository, because a plugin that needs an account is one that fails on the day the account does.",
  },
];
