// GENERATED by scripts/roadmap.mjs from docs/ROADMAP.md, through roadkeep. Do not edit.
// `npm run generate` rewrites this file; `npm test` fails if it drifted from the roadmap.

export interface GeneratedBlock {
  /** the single letter the roadmap files it under */
  block: string;
  title: string;
  /** lines still open in that block */
  open: number;
}

export interface GeneratedTask {
  id: string;
  block: string;
  /** the failure the line exists to remove, in the roadmap's own words */
  symptom: string;
  /** the measurement or the argument behind it */
  why: string;
  deps: string[];
}

export interface GeneratedNonGoal {
  lead: string;
  why: string;
}

export const generatedBlocks: GeneratedBlock[] = [
  { block: "A", title: "What a tool call costs the turn", open: 3 },
  { block: "B", title: "Seeing the result cheaply", open: 0 },
  { block: "C", title: "The asset compiler", open: 0 },
  { block: "D", title: "Fetching from a paid service without surprise", open: 0 },
  { block: "E", title: "One world with the engine", open: 0 },
  { block: "F", title: "Motion", open: 0 },
  { block: "G", title: "Geometry as a declaration", open: 1 },
  { block: "H", title: "Proof on a real game", open: 4 },
];

export const generatedTasks: GeneratedTask[] = [
  {
    id: "PW61",
    block: "A",
    symptom: "the site understands one of the backlog's three dep forms, so a block or a range becomes a dangling id",
    why: "waitingOn keeps the first whitespace token, so a `Block G` dep becomes `Block`, and the gate reports a missing task rather than a grammar it cannot read.",
    deps: [],
  },
  {
    id: "PW62",
    block: "A",
    symptom: "a render resolves its noise floor without naming its rung, so a sphere is judged at the floor measured for a final",
    why: "The same call hands the rung to the measurer and withholds it from the bar, so the noisiest rung gets the tightest floor and a flat sphere passes PW42's check.",
    deps: [],
  },
  {
    id: "PW63",
    block: "A",
    symptom: "three of Cottony's rig constants share a name with a plugin parameter that means something else",
    why: "A port that copies fill, key or ambient across is accepted and renders the wrong picture, because the guard refuses an axis nothing takes and cannot see one whose name is taken.",
    deps: [],
  },
  {
    id: "PW60",
    block: "G",
    symptom: "a declaration is read, resolved and reported on, and nothing turns one into a mesh",
    why: "Every op function, the build order and the report that consumes the result all ship, and no call in the package produces the spec's own worked example.",
    deps: [],
  },
  {
    id: "PW54",
    block: "H",
    symptom: "a Cottony shape is a bmesh program that exists only inside a bake, so nothing can read, diff or search it",
    why: "solid.py is 283 lines of geometry as code, and it carries a second copy of the bevelled-boolean lesson, which is a copy that will drift.",
    deps: ["PW60"],
  },
  {
    id: "PW57",
    block: "H",
    symptom: "every Cottony look gate restates its own floor, so no asset has a bar a search can aim at",
    why: "Five check scripts measure after the render is spent, which is a verdict and never a target, and a threshold moved in one of them is invisible to the rest.",
    deps: ["PW53"],
  },
  {
    id: "PW58",
    block: "H",
    symptom: "nothing a game ships has been through the skeleton, the clip or the sprite sheet",
    why: "Cottony's whole motion surface is one mesh squashed and re-rendered, so Block F's claim rests on synthetic figures whose bones are where the plan put them.",
    deps: [],
  },
  {
    id: "PW59",
    block: "H",
    symptom: "nothing says how much of Cottony still does its own version of what the plugin does",
    why: "Adoption is asserted per asset, so a hand-rolled rig, gate or runner can come back without anything failing, and 100% stays an opinion.",
    deps: ["PW53", "PW54", "PW56", "PW57", "PW58"],
  },
];

export const generatedNonGoals: GeneratedNonGoal[] = [
  {
    lead: "A graphical editor",
    why: "The caller here is an agent in a terminal, so a surface that needs a person at a screen to operate is one the agent cannot use at all.",
  },
  {
    lead: "Replacing Blender, Godot or the generative service",
    why: "Those three already do the work; what is missing is the loop around them, so this orchestrates and measures and never re-implements a renderer, an engine or a mesh generator.",
  },
  {
    lead: "Spending money on the agent's own judgement",
    why: "A fetch draws on a real balance, so the ceiling is a person's to set and the plugin's job is to make a spend bounded and visible, never to decide one is worth it.",
  },
  {
    lead: "One project's palette, rig or paths compiled in",
    why: "Cottony is the first consumer and not the specification, so anything it needs that a second project would not is configuration, and a default that cannot be overridden is a defect.",
  },
  {
    lead: "A hosted service or an account to sign into",
    why: "Everything runs on the developer's machine against files in their own repository, because a plugin that needs an account is one that fails on the day the account does.",
  },
];

/** Lines set aside rather than shipped. They keep their ids, and are still waited on. */
export const generatedPaused: string[] = ["PW36", "PW53", "PW56"];
